version: '3'
services:
  db:
    image: postgres:13.1-alpine
    restart: always
    ports:
      - '5438:5432'
    environment:
      POSTGRES_DB: appstore
      POSTGRES_USER: appstore
      POSTGRES_PASSWORD: appstore
